apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: container-registry
  namespace: container-registry
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`registry.k3s.{{ domain_name }}`)
      kind: Rule
      services:
        - name: container-registry-docker-registry
          port: 5000
