apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: container-registry
  namespace: container-registry
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0" 
spec:
  rules:
  - host: registry.k8s.{{ domain_name }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: container-registry-docker-registry
            port:
              number: 5000
