---
- name: Install and configure nginx for static website hosting
  hosts: bastion
  vars_files:
    - "{{ env }}.yml"
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
    - name: Remove default nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: Add nginx configuration
      copy:
        src: files/10_kubernetes_reverse_proxy_lb
        dest: /etc/nginx/sites-available/
        owner: root
        group: root
        mode: '0644'
    - name: Enable website configuration
      file:
        src: /etc/nginx/sites-available/10_kubernetes_reverse_proxy_lb
        dest: /etc/nginx/sites-enabled/10_kubernetes_reverse_proxy_lb
        state: link
    - name: Ensure nginx is running
      systemd:
        name: nginx
        state: started
        enabled: yes
